# PR Path-based Labeler (Auftrag 21)
# Used with actions/labeler to auto-label PRs based on changed file paths

# Frontend
frontend:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/app/**'
          - 'src/components/**'
          - 'frontend/**'

# Backend / API
api:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/app/api/**'
          - 'src/lib/**'

# Database
db:
  - changed-files:
      - any-glob-to-any-file:
          - 'prisma/**'
          - 'supabase/**'

# CI/CD
ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'

# Documentation
docs:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**'
          - 'NOTES/**'
          - '*.md'

# Tests
tests:
  - changed-files:
      - any-glob-to-any-file:
          - 'tests/**'
          - '**/*.test.ts'
          - '**/*.test.tsx'

# Config
config:
  - changed-files:
      - any-glob-to-any-file:
          - '*.config.*'
          - '.eslintrc*'
          - '.prettierrc*'
          - 'tsconfig*'

# Tools / Scripts
tooling:
  - changed-files:
      - any-glob-to-any-file:
          - 'tools/**'
          - 'scripts/**'

# Dependencies
dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'package.json'
          - 'pnpm-lock.yaml'
