name: Bug Report
description: DOS-konforme Fehlermeldung
labels: ["type:fix"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Bereich
      options:
        - shop
        - werkstatt
        - autohandel
        - shared
        - infra
    validations:
      required: true
  - type: dropdown
    id: funnel
    attributes:
      label: Funnel-Schritt
      options:
        - Awareness
        - Education
        - Consideration
        - Conversion
        - Retention
  - type: dropdown
    id: criticality
    attributes:
      label: Kritikalit채t
      options:
        - blocker
        - high
        - medium
        - low
    validations:
      required: true
  - type: textarea
    id: reproducibility
    attributes:
      label: Reproduzierbarkeit
      placeholder: Schritte zum Reproduzieren des Fehlers...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Erwartetes Verhalten
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Tats채chliches Verhalten
    validations:
      required: true
  - type: textarea
    id: events
    attributes:
      label: Betroffene Events
  - type: input
    id: sentry
    attributes:
      label: Sentry Link
  - type: textarea
    id: root_cause
    attributes:
      label: Root Cause Analyse (Pflicht)
      description: Warum ist dieser Fehler aufgetreten?
    validations:
      required: true
  - type: checkboxes
    id: validation
    attributes:
      label: Fix-Abnahme
      options:
        - label: Keine Sekund채rprobleme identifiziert
        - label: Regression gepr체ft
        - label: STATE aktualisiert
