name: Bug Report
description: Fehlerbericht nach DOS-Standard
body:
  - type: dropdown
    id: area
    attributes:
      label: Bereich
      options:
        - shop
        - werkstatt
        - autohandel
        - shared
    validations:
      required: true
  - type: textarea
    id: funnel_step
    attributes:
      label: Funnel-Schritt
    validations:
      required: true
  - type: dropdown
    id: criticality
    attributes:
      label: Kritikalit채t
      options:
        - blocker
        - high
        - medium
        - low
    validations:
      required: true
  - type: textarea
    id: reproducibility
    attributes:
      label: Reproduzierbarkeit
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Erwartetes Verhalten
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Tats채chliches Verhalten
    validations:
      required: true
  - type: textarea
    id: events
    attributes:
      label: Betroffene Events
  - type: input
    id: sentry
    attributes:
      label: Sentry Link
  - type: textarea
    id: rca
    attributes:
      label: Root Cause Analyse (Pflicht)
    validations:
      required: true
  - type: checkboxes
    id: fix_acceptance
    attributes:
      label: Fix-Abnahme
      options:
        - label: Keine Sekund채rprobleme
        - label: Regression gepr체ft
        - label: STATE aktualisiert
