name: 🐛 Bug Report
description: Fehler melden
title: "fix: "
labels: ["type:bug", "status:triage"]
body:
  - type: input
    id: area
    attributes:
      label: Bereich
      description: Welcher Bereich ist betroffen?
      placeholder: "shop / werkstatt / autohandel / infra"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Beschreibung
      description: Was ist passiert?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Erwartetes Verhalten
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Schritte zur Reproduktion
      placeholder: |
        1. Gehe zu ...
        2. Klicke auf ...
        3. Fehler erscheint
  - type: dropdown
    id: priority
    attributes:
      label: Priorität
      options:
        - priority:critical
        - priority:high
        - priority:medium
        - priority:low
    validations:
      required: true
