name: Feature Request
description: Neues Feature DOS-konform implementieren
labels: ["type:feat"]
body:
  - type: markdown
    attributes:
      value: |
        Bitte füllen Sie alle Pflichtfelder aus, um die DOS v1.1 Compliance sicherzustellen.
  - type: dropdown
    id: area
    attributes:
      label: Bereich
      options:
        - shop
        - werkstatt
        - autohandel
        - shared
        - infra
    validations:
      required: true
  - type: checkboxes
    id: funnel
    attributes:
      label: Funnel-Zuordnung (Pflicht)
      options:
        - label: Awareness
        - label: Education
        - label: Consideration
        - label: Conversion
        - label: Retention
    validations:
      required: true
  - type: textarea
    id: kpi
    attributes:
      label: KPI-Ziel
      description: z. B. Add-to-Cart Rate +1%
      placeholder: Beschreiben Sie das messbare Ziel dieses Features.
    validations:
      required: true
  - type: textarea
    id: events
    attributes:
      label: Betroffene Events
      description: Welche Tracking-Events werden neu erstellt oder geändert?
  - type: checkboxes
    id: security
    attributes:
      label: Security-Bewertung
      options:
        - label: RLS geprüft/notwendig
        - label: DSGVO konform (keine PII in Tracking)
        - label: Zahlungsrelevanz vorhanden
  - type: checkboxes
    id: done
    attributes:
      label: Done-Kriterien
      options:
        - label: UI-Regel erfüllt (src/components/ui, 8px Grid)
        - label: Tracking integriert (src/lib/events.ts)
        - label: Lighthouse ≥ 90 (LCP, CLS, INP, TTFB)
        - label: Tests ergänzt (Unit/E2E)
        - label: Dokumentation (STATE/KNOWLEDGE) aktualisiert
    validations:
      required: true
