name: Feature request
description: Propose a product or engineering improvement
title: "[FEATURE]: "
labels: ["type:feature", "status:triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: Which user or business problem should be solved?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: true
