name: Feature Request
description: Neues Feature DOS-konform implementieren
title: "[FEAT]: "
labels: ["type:feature"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Bereich
      options:
        - shop
        - werkstatt
        - autohandel
        - shared
    validations:
      required: true
  - type: checkboxes
    id: funnel
    attributes:
      label: Funnel-Zuordnung (Pflicht)
      options:
        - label: Awareness
        - label: Education
        - label: Consideration
        - label: Conversion
        - label: Retention
    validations:
      required: true
  - type: textarea
    id: kpi
    attributes:
      label: KPI-Ziel
      placeholder: "z. B. Add-to-Cart Rate +1%"
    validations:
      required: true
  - type: textarea
    id: events
    attributes:
      label: Betroffene Events
  - type: checkboxes
    id: security
    attributes:
      label: Security-Bewertung
      options:
        - label: RLS geprüft
        - label: DSGVO konform
        - label: Zahlungsrelevanz vorhanden
  - type: checkboxes
    id: done
    attributes:
      label: Done-Kriterien
      options:
        - label: UI-Regel erfüllt
        - label: Tracking integriert
        - label: Lighthouse ≥ 90
        - label: Tests ergänzt
        - label: Dokumentation (STATE/KNOWLEDGE) aktualisiert
    validations:
      required: true
