name: ✨ Feature Request
description: Neue Funktion vorschlagen
title: "feat: "
labels: ["type:feature", "status:triage"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Bereich
      options:
        - area:shop (Carvantooo #FFB300)
        - area:werkstatt (OpenCarBox #FFA800)
        - area:autohandel (OpenCarBox #FFA800)
        - area:infra
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: Welches Problem löst dieses Feature?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Vorgeschlagene Lösung
    validations:
      required: true
  - type: textarea
    id: kpi
    attributes:
      label: KPI-Auswirkung
      description: Welche KPI-Ziele werden beeinflusst?
  - type: dropdown
    id: milestone
    attributes:
      label: Phase
      options:
        - "Phase 1: Core Commerce (MVP)"
        - "Phase 2: Feature Complete"
        - "Phase 3: Production Ready"
