name: KPI Alert
description: Automatisch erstellter Alert bei KPI-Unterschreitung
labels: ["type:incident", "kpi-alert"]
body:
  - type: markdown
    attributes:
      value: |
        Dieser Issue wurde automatisch erstellt, da eine KPI den Schwellenwert unterschritten hat.
  - type: input
    id: kpi
    attributes:
      label: KPI
    validations:
      required: true
  - type: input
    id: current_value
    attributes:
      label: Aktueller Wert
  - type: input
    id: target_value
    attributes:
      label: Zielwert
  - type: input
    id: timeframe
    attributes:
      label: Zeitfenster
  - type: dropdown
    id: funnel
    attributes:
      label: Funnel-Schritt
      options:
        - Awareness
        - Education
        - Consideration
        - Conversion
        - Retention
  - type: checkboxes
    id: analysis
    attributes:
      label: Analyse
      options:
        - label: Event-Tracking korrekt?
        - label: UX-Regression identifiziert?
        - label: Performance-Drop festgestellt?
